const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('app.js','utf8');new vm.Script(source);
const ctx=vm.createContext({XLSX:require('../vendor/xlsx.full.min.js')});
for(const name of ['isNewsMail','mailDate','normHead','detectHeaders','getVal','parseSheet']){const line=source.split('\n').find(l=>l.trim().startsWith('function '+name+'('));assert(line,name);vm.runInContext(line,ctx);}
assert(ctx.isNewsMail({campaign:'Gosfinansi_letter_news_GF_digest_u'}));
assert(ctx.isNewsMail({campaign:'letter_news_goszakaz_regular_news_digest_v'}));
assert(!ctx.isNewsMail({campaign:'other_digest_news'}));
const sorted=[{date:'2026-09-16',time:'15:00'},{date:'2026-09-17',time:'9:00'},{date:'2026-09-17',time:'13:00'}].sort((a,b)=>ctx.mailDate(b).localeCompare(ctx.mailDate(a)));
assert.equal(sorted[0].time,'13:00');assert.equal(sorted[2].date,'2026-09-16');
const sheet=ctx.XLSX.utils.aoa_to_sheet([['Номер действия','sl_api_nr','Анализ - Расшифровка звонков','Кол-во продаж'],['123','456','Клиент: нужен образец документа',1]]);
const parsed=ctx.parseSheet(sheet);assert.equal(parsed.records.length,1);assert.equal(parsed.records[0].transcript,'Клиент: нужен образец документа');assert.equal(parsed.records[0].sale,true);
const s=fs.readFileSync('DashboardTabs.gs','utf8');new vm.Script(s);
assert(!source.includes('data-page=\\"demo\\"'));
console.log('PASS: strict NEWS, newest-first ordering, XLSX import mapping, source syntax, removed tab');
const server=vm.createContext({Session:{getActiveUser:()=>({getEmail:()=> 'owner@example.com'}),getEffectiveUser:()=>({getEmail:()=> 'owner@example.com'})},APP:{sendsaySheet:'data'},openStorage_:()=>({getSheetByName:()=>({getDataRange:()=>({getDisplayValues:()=>[['File ID','Доставлено','Уник. открытия','Уник. клики'],['a','10000','99','19']]})})}),readImportedEmails_:()=>[{id:'import-a'}],number_:Number,round_:(v,d)=>Math.round(v*10**d)/10**d});vm.runInContext(s,server);server.dashboardDemoRows_=()=>[];server.dashboardMatchMails_=x=>x;const rates=server.getMailRegistryUi().emails[0];assert.equal(rates.openRate,.99);assert.equal(rates.clickRate,.19);console.log('PASS: sub-one-percent rates are not multiplied by 100');
const attribution=vm.createContext({demoCampaignKey_:v=>String(v).toLowerCase().replace(/[^a-zа-я0-9]+/g,'_').replace(/^letter_demo_20\d{2}_\d{2}_\d{2}_/,'')});vm.runInContext(s,attribution);
const facts=[{key:'letter_demo_2026.09.01_letter_demo_example_01.09.2026',product:'ГЗ Система',source:'Факт',weeks:[{week:35,red:99,yellow:99,green:99},{week:36,red:3,yellow:2,green:1},{week:37,red:0,yellow:1,green:2}]}];
const matched=attribution.dashboardMatchMails_([{campaign:'letter_demo_example_01.09.2026',week:36},{campaign:'letter_demo_example_01.09.2026',week:36},{campaign:'other',week:36}],facts);
assert.equal(matched[0].green,3);assert.equal(matched[0].red,3);assert.equal(matched[0].demoEvidence[0].product,'ГЗ Система');assert.match(matched[0].note,/общий/);assert.equal(matched[2].hasDemoData,false);
console.log('PASS: fresh campaign attribution, later weeks, shared tags, unmatched facts');
const demand=vm.createContext({n:Number});vm.runInContext(source.slice(source.indexOf('function demandMailTopics('),source.indexOf('async function loadDemand(')),demand);
const sample={subject:'Образец документа',date:'2026-09-01',campaign:'campaign',hasDemoData:true,demoEvidence:[{sourceUrl:'https://example.test/#row=1',product:'ГЗ Система',red:3,yellow:2,green:1}]};
const demandTopics=demand.demandMailTopics([sample,sample,{...sample,demoEvidence:[{...sample.demoEvidence[0],sourceUrl:'https://example.test/#row=2',green:2}]}]);
assert.equal(demandTopics.length,1);assert.equal(demandTopics[0].green,3);assert.equal(demandTopics[0].letters.length,2);console.log('PASS: demand grouping does not double-count repeated campaign reports');
const materials=attribution.dashboardMaterials_('<a href="https://www.budgetnik.ru/news/125090-example?x=1">Нейросеть</a><a href="https://www.budgetnik.ru/art/125090-example">Статья</a><a href="https://www.pro-goszakaz.ru/news/125090-example">Закупки</a>');
assert.equal(materials.length,3);assert.equal(materials[0].title,'Нейросеть');
const mr=attribution.dashboardMaterialRows_({product:'ГФ Периодика'},materials,[{product:'ГФ Периодика',key:'news',term:'125090',sourceUrl:'source',weeks:[{week:36,red:1,yellow:2,green:3},{week:37,red:0,yellow:1,green:1}]},{product:'ГЗ Периодика',key:'news',term:'125090',weeks:[]}]);
assert.equal(mr.length,1);assert.equal(mr[0].values.green,4);
const news={campaign:'Gosfinansi_letter_news_GF_digest_u',date:'2026-09-01',materialData:{rows:mr}};
assert.equal(demand.demandMailTopics([news,news])[0].green,4);
assert(!JSON.parse(source.match(/document.body.innerHTML=(".*");/)[1]).includes('data-page="calls"'));
console.log('PASS: material ID, type and domain matching, full-period totals, repeated material deduplication, calls hidden');
const wrapped=attribution.dashboardMaterials_(`<a href="https://app.sendsay.ru/[%%20action_autologin_utm('https://www.budgetnik.ru/news/124482-example')%20%]">=D0=90=D0=BA=D1=82 0510460</a>`);
assert.equal(wrapped[0].title,'Акт 0510460');assert.equal(wrapped[0].url,'https://www.budgetnik.ru/news/124482-example');
console.log('PASS: Sendsay template links preserve Russian material titles');
const editorial=attribution.dashboardEditorialSections_('18 сентября\nТема 18\nТекст\u000b17 сент\nТема 17\nПолный текст\nдополнительная рассылка 17.09.\nДополнительное письмо\n16 сентября\nТема 16');
assert.equal(attribution.dashboardEditorialMatch_(['17.09.2026','','','Тема 17'],editorial).text,'Тема 17\nПолный текст');
assert.equal(attribution.dashboardEditorialMatch_(['17.09.2026','','','Другая тема'],editorial).subjectMatches,false);
assert(attribution.dashboardEditorialMatch_(['15.09.2026','','','Нет'],editorial).error);
assert(attribution.dashboardEditorialMatch_(['17.09.2026','','','Тема'],[...editorial,editorial[1]]).error);
console.log('PASS: editorial date matching, extra-mail exclusion, missing/ambiguous originals, changed subjects');
